[package]
name = "sys-info"
version = "0.1.0"
authors = ["mkdirlove <mkdirlove@lspu.edu.ph>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sys-info = "0.9"
nix = "0.21.0"
chrono = "0.4"
